### ISSUE TITLE
Support reconnecting websockets for node module

### ISSUE THREAD

**Issue by skepticfx** [CaliDog/certstream-js#3]
This is a great tool! Thank you.

I see that the browser version uses the `reconnectingwebsocket` module, however the node module only supports the vanilla `ws` module. Thus CertStream server restarts won't go well with the nodejs clients.

**Comment by Fitblip** [comment]
Hey @skepticfx - IIRC I spent a decent chunk of time messing with this trying to get reconnectingWebsocket working properly with the nodejs client and gave up out of frustration. 

Probably not the answer you were looking for, but if you want to submit a PR I'm more than happy to merge/take a look! :)

**Comment by skepticfx** [comment]
Sure! Working on a fix, will send the PR soon :)
